from pathlib import Path

p=Path('src/filing_parser.py')
s=p.read_text(encoding='utf-8')
s=s.replace('''    cover_text = full_text[:30000]\n\n    ticker_match = re.search(''','''    cover_text = full_text[:100000]\n\n    ticker_match = re.search(''',1)
s=s.replace('''        r"initial public offering price(?:\\s+per\\s+share)?"\n        r"\\s*(?:is|:)?\\s*\\$\\s*(\\d{1,4}(?:\\.\\d{1,2})?)",\n        r"public offering price(?:\\s+per\\s+share)?"\n        r"\\s*(?:is|:)?\\s*\\$\\s*(\\d{1,4}(?:\\.\\d{1,2})?)",''','''        r"initial public offering price(?:\\s+per\\s+share)?"\n        r"\\s*(?:is|of|:)?\\s*\\$\\s*(\\d{1,4}(?:\\.\\d{1,2})?)",\n        r"public offering price(?:\\s+per\\s+share)?"\n        r"\\s*(?:is|of|:)?\\s*\\$\\s*(\\d{1,4}(?:\\.\\d{1,2})?)",''',1)
old='''    cover_text = soup.get_text(" ", strip=True)[:30000]\n    patterns = [\n        r"principal executive offices? (?:are|is) located at [^.;]{0,220}?\\b([A-Za-z .'-]{2,60}),\\s*([A-Z]{2})\\s+\\d{5}(?:-\\d{4})?",\n        r"principal executive offices?[^.;]{0,220}?\\b([A-Za-z .'-]{2,60}),\\s*([A-Z]{2})\\s+\\d{5}(?:-\\d{4})?",\n        r"address of principal executive offices?[^.;]{0,220}?\\b([A-Za-z .'-]{2,60}),\\s*([A-Z]{2})\\s+\\d{5}(?:-\\d{4})?",\n    ]\n'''
new='''    cover_text = soup.get_text(" ", strip=True)[:100000]\n    # Registration/prospectus covers often put the address immediately before\n    # the parenthetical label rather than in a sentence saying "located at".\n    label = re.search(r"\\(Address[^)]*principal executive offices\\)", cover_text, re.I)\n    if label:\n        preceding = cover_text[max(0, label.start()-600):label.start()]\n        address_matches = re.findall(r"\\b([A-Za-z][A-Za-z .'-]{1,50}),\\s*([A-Z]{2})\\s+\\d{5}(?:-\\d{4})?", preceding)\n        if address_matches:\n            city, state = address_matches[-1]\n            city = " ".join(city.split()).strip(" ,")\n            if city:\n                return f"{city}, {state.upper()}"\n    patterns = [\n        r"principal executive offices? (?:are|is) located at [^.;]{0,220}?\\b([A-Za-z .'-]{2,60}),\\s*([A-Z]{2})\\s+\\d{5}(?:-\\d{4})?",\n        r"principal executive offices?[^.;]{0,220}?\\b([A-Za-z .'-]{2,60}),\\s*([A-Z]{2})\\s+\\d{5}(?:-\\d{4})?",\n        r"address of principal executive offices?[^.;]{0,220}?\\b([A-Za-z .'-]{2,60}),\\s*([A-Z]{2})\\s+\\d{5}(?:-\\d{4})?",\n    ]\n'''
assert old in s
s=s.replace(old,new,1)
old='''    full_text = soup.get_text(" ", strip=True)\n    cover_text = full_text[:30000]\n\n    patterns = [\n        r"offering\\s+([\\d,]{4,})\\s+shares",\n'''
new='''    full_text = soup.get_text(" ", strip=True)\n    cover_text = full_text[:100000]\n\n    # When both issuer and selling stockholders participate, total IPO size is\n    # the sum of both blocks. This is the relevant gross liquidity-event size.\n    combined = re.search(\n        r"we are offering\\s+([\\d,]{4,})\\s+shares[^.]{0,1000}?selling stockholders?[^.]{0,500}?offering(?: an additional)?\\s+([\\d,]{4,})\\s+shares",\n        cover_text, re.I\n    )\n    if combined:\n        return int(combined.group(1).replace(",", "")) + int(combined.group(2).replace(",", ""))\n\n    patterns = [\n        r"offering\\s+([\\d,]{4,})\\s+shares",\n'''
assert old in s
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')

p=Path('src/test_filing_parser.py')
s=p.read_text(encoding='utf-8')
if 'test_lyntris_style_final_terms' not in s:
    s += '''\n\nclass LyntrisFinalTermsQaTests(unittest.TestCase):\n    def test_lyntris_style_final_terms(self):\n        from bs4 import BeautifulSoup\n        import filing_parser\n        html="""<html><body>Lyntris Inc. 3130 Fairview Park Dr., Suite 230 Falls Church, VA 22042 (Address, including zip code, and telephone number, including area code, of registrant's principal executive offices) We are offering 5,714,286 shares of common stock and the selling stockholders are offering an additional 11,285,714 shares of common stock. The initial public offering price of $17.50 per share.</body></html>"""\n        soup=BeautifulSoup(html, "html.parser")\n        self.assertEqual(filing_parser.extract_cover_page_data(soup)["offering_price"], 17.50)\n        self.assertEqual(filing_parser.extract_offering_size(soup), 17_000_000)\n        self.assertEqual(filing_parser.extract_principal_office_location(soup), "Falls Church, VA")\n'''
p.write_text(s,encoding='utf-8')
